export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const RT_ACTIVE_USERS = 'RT_ACTIVE_USERS';
export const RT_DOWNLOADS = 'RT_DOWNLOADS';
export const RT_SESSION_DURATION = 'RT_SESSION_DURATION';
export const RT_PAID_USERS = 'RT_PAID_USERS';
export const DAILY_ACTIVE_USERS = 'DAILY_ACTIVE_USERS';
export const DAILY_DOWNLOADS = 'DAILY_DOWNLOADS';


